"""Os modelos e as migrations descrevem o mesmo banco.

`alembic check` responde isso, e o projeto passou meses com ele VERMELHO por
deriva acumulada: cinco check constraints e um indice parcial existiam apenas
nas migrations, sem declaracao nos modelos.

Duas consequencias, e a segunda e' a pior. A primeira e' que um banco criado por
`Base.metadata.create_all` nascia sem eles - foi assim que oito indices, entre
eles a unica garantia de unicidade de sessao ativa, sumiram de desenvolvimento
sem ninguem perceber. A segunda e' que um verificador que sempre falha deixa de
ser lido: quando a deriva passou a ser de verdade - colunas acrescentadas a uma
migration ja aplicada, um nome de constraint truncado pelo Postgres -, o
comando ja estava vermelho havia tanto tempo que a saida nao dizia nada.

Este teste existe para o vermelho voltar a significar alguma coisa.
"""

from __future__ import annotations

import asyncio

import pytest

from app.core.config import settings


async def test_modelos_e_migrations_descrevem_o_mesmo_banco(url_de_teste, preparar_banco):
    """Nao pode haver diferenca entre o metadata e o schema das migrations.

    Falhou? A saida do alembic diz o que sobrou de cada lado. Os dois desfechos
    possiveis sao:

    - A migration criou algo que o modelo nao declara. Declare no
      `__table_args__` do modelo, com o nome SEM o prefixo `ck_<tabela>_` - a
      NAMING_CONVENTION o acrescenta, e escrever o nome completo o duplica.
    - O modelo mudou e falta migration. Gere uma; nao edite migration ja
      aplicada, porque o schema passa a depender de QUANDO cada banco rodou.
    """
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected

    from alembic import command

    # Mesmo caminho do conftest: o `env.py` sobrescreve `sqlalchemy.url` no
    # import, entao apontar o singleton e' o unico jeito que funciona.
    anterior = settings.database_url_override
    settings.database_url_override = url_de_teste
    try:
        cfg = Config("alembic.ini")
        # Thread propria: o `env.py` chama `asyncio.run()`, que recusa rodar
        # dentro de um laco ja em execucao - e o pytest-asyncio abriu o dele.
        try:
            await asyncio.to_thread(command.check, cfg)
        except AutogenerateDiffsDetected as diferenca:
            pytest.fail(
                "modelos e migrations divergem:\n"
                f"{diferenca}\n\n"
                "Declare no `__table_args__` do modelo, ou gere a migration que falta."
            )
    finally:
        settings.database_url_override = anterior
